### ISSUE TITLE
我只有2个问题

### ISSUE THREAD

**Issue by Root-FTW** [AstraSurge/gpteams#14]
我只有两个问题：

1.- 目前该项目在主项目后面有51个提交，你会更新吗？

2.- 是否已经可以在vercel中一键部署，并在vercel中添加所有变量（包括firebase）？

-----

I only have 2 questions:

1.- At this moment the project is 51 commits behind the main project, will you update it?

2.- Is it already possible to deploy it in vercel with 1 click and adding all the variables (including firebase) in vercel?

**Comment by suikodev** [comment]
1. Already updated. Starting from this week, we will no longer merge updates from the upstream. The differences between the two projects' codebases are growing, making the merge cost increasingly higher, and many upstream updates are not very significant, or GPTeams will have better implementation methods. However, I will still continue to keep an eye on the upstream updates.
2. GPTeams cannot support Vercel's Hobby Plan because the [limits of Vercel's Hobby Plan](https://vercel.com/docs/concepts/limits/overview#general-limits) make it impossible to deploy GPTeams.
3. We are currently looking for another platform that allows easy and free deployment of GPTeams.

**Comment by Root-FTW** [comment]
> 1. Already updated. Starting from this week, we will no longer merge updates from the upstream. The differences between the two projects' codebases are growing, making the merge cost increasingly higher, and many upstream updates are not very significant, or GPTeams will have better implementation methods. However, I will still continue to keep an eye on the upstream updates.
> 2. GPTeams cannot support Vercel's Hobby Plan because the [limits of Vercel's Hobby Plan](https://vercel.com/docs/concepts/limits/overview#general-limits) make it impossible to deploy GPTeams.
> 3. We are currently looking for another platform that allows easy and free deployment of GPTeams.

Do you know if the RailWay "developer" plan would be enough?
https://railway.app/pricing

I have that plan and I think it could be possible.

The plan is 5USd per month, but railway gives you 5USD per month, so it's practically free.

I set up the main project on railway, I gave it to 50 people on the weekend and they used it and I didn't spend a dollar, it's practically free.

**Comment by suikodev** [comment]
I will devote time this week to research the possibility of deploying GPTeams to Railway, I promise.
